import rocky from '../../../../IMG/caro1.jpg'
const data =[
    {
        id:1,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:2,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:3,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:3,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:4,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:5,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:6,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:7,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:8,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:9,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:10,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:11,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:12,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:13,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:14,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:15,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:16,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
    {
        id:17,
        src:rocky,
        name:"Rocky",
        age:5,
        vaccination:"completed"
    },
]
export default data;